### ISSUE TITLE
bug: Error: Database is not open when evaluating contract state

### ISSUE THREAD

**Issue by dtfiedler** [warp-contracts/warp-contracts-lmdb#26]
Environment:
- warp-contracts: 1.4.22
- warp-contracts-lmdb: 1.1.10
- NodeJS: v18.17.2

Issue:
Warp fails to read from LMDB database:
- contractTxId: `E-pRI1bokGWQBqHnbut9rsHSt9Ypbldos3bAtwg4JMc`

Setup:
```js
const warp = WarpFactory.forMainnet(defaultCacheOptions,
  true,
  arweave,
).useStateCache(
  new LmdbCache(defaultCacheOptions,
    {
      maxEntriesPerContract: 1000,
      minEntriesPerContract: 0,
    },
  ),
);
```

The issue is not consistent, but some interactions cause the following error when evaluating contract state:
```
2023-11-06T17:14:43.819Z FATAL [HandlerBasedContract] Error while interacting with contract [{
    type: 'exception',
    error: 'Error: Database is not open\n' +
    ' at maybeOpened (/usr/src/app/node_modules/abstract-level/abstract-level.js:133:18)\n' +
    ' at /usr/src/app/node_modules/abstract-level/abstract-level.js:160:13\n' +
    ' at process.processTicksAndRejections (node:internal/process/task_queues:77:11)'
}]
```

**Comment by dtfiedler** [comment]
may just require `inMemory` to be `false `- testing and will update here if that resolves the issue (it's a large cache)

**Comment by dtfiedler** [comment]
unfortunately setting the `inMemory` to false does not fix the issue - multiple evaluations against `lmdb` in a short amount of time seems to be the primary cause
